-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A
INNER JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY A.ADDRESS
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;

# SELECT * FROM REST_INFO
# WHERE ADDRESS LIKE '서울%';

# SELECT * FROM REST_REVIEW
# WHERE REST_ID = 00003;

# SELECT * FROM REST_REVIEW
# WHERE REST_ID LIKE '%2%';

# SELECT * FROM REST_REVIEW
# WHERE REST_ID LIKE '%3%';

# SELECT * FROM REST_REVIEW
# WHERE REST_ID LIKE '%4%';