-- 코드를 작성해주세요
WITH ECOLI_ET AS(
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    B.YEAR,
    ABS(B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA AS A, ECOLI_ET AS B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR ASC, YEAR_DEV ASC;