SELECT 
    SUM(G.SCORE) SCORE,
    E.EMP_NO EMP_NO,
    E.EMP_NAME EMP_NAME,
    E.POSITION POSITION,
    E.EMAIL EMAIL
FROM HR_EMPLOYEES E 
JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
WHERE G.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;